<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.koiki.walkingskeleton</groupId>
    <artifactId>koiki-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../../koiki-parent/pom.xml</relativePath>
  </parent>

  <artifactId>ws-architecture-contract</artifactId>
  <packaging>jar</packaging>

  <name>KOIKI Walking Skeleton Architecture Contract</name>

  <dependencies>
    <dependency>
      <groupId>org.jspecify</groupId>
      <artifactId>jspecify</artifactId>
    </dependency>
  </dependencies>

</project>
