spring.application.name=performance-koiki
spring.jpa.hibernate.ddl-auto=validate
koiki.environment=performance
management.endpoint.health.group.readiness.include=readinessState,db
logging.level.root=WARN
logging.level.org.koikifw.performance.fixture=INFO
