spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
koiki.identity.local-authentication.enabled=true
koiki.identity.login-attempt.source-protection=EXTERNAL
server.address=127.0.0.1
server.servlet.session.cookie.secure=false
spring.main.banner-mode=off
logging.level.org.flywaydb=WARN
logging.level.org.hibernate.orm.connections.pooling=WARN
