spring.application.name=performance-bare
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration/customer
spring.mvc.problemdetails.enabled=true
spring.mvc.apiversion.use.path-segment=1
spring.mvc.apiversion.required=true
spring.mvc.apiversion.detect-supported=false
spring.mvc.apiversion.supported=1
logging.level.root=WARN
logging.level.org.koikifw.performance.fixture=INFO
