spring.main.web-application-type=none
spring.jpa.hibernate.ddl-auto=none
spring.modulith.events.jdbc.schema-initialization.enabled=false
spring.modulith.events.completion-mode=UPDATE
logging.level.org.springframework.jdbc.core=INFO
logging.level.org.hibernate.SQL=INFO
